Various updates

diff --git a/runcoms/zshrc b/runcoms/zshrc
--- a/runcoms/zshrc
+++ b/runcoms/zshrc
@@ -15,20 +15,19 @@ fi
 ###########
 # Aliases #
 ###########
-alias ea='e ~/.zprezto/runcoms/zshrc && source ~/.zshrc'
+alias ea='e ~/.zprezto/runcoms && source ~/.zshrc'
 
 alias a2c='aria2c -x10 -s10 -k1M'
 
 alias mt='multitail -cT ansi'
 
-alias cup="brew upgrade; for app in \$(brew cask list); do cver=\"\$(brew cask info \"\${app}\" | head -n 1 | cut -d \" \" -f 2)\"; ivers=\$(ls -1 \"/usr/local/Caskroom/\${app}/.metadata/\" | tr '\n' ' ' | sed -e 's/ \$//'); aivers=(\${ivers}); nvers=\$(echo \${#aivers[@]}); echo \"* \${app}: \${ivers} -> \${cver}\"; if [[ \${nvers} -eq 1 ]]; then echo \"\${ivers}\" | grep -q \"^\${cver}\$\" && { continue; }; fi; brew cask uninstall \"\${app}\" --force; brew cask install \"\${app}\"; done"
+alias cup="brew update && brew upgrade && for app in \$(brew cask list); do cver=\"\$(brew cask info \"\${app}\" | head -n 1 | cut -d \" \" -f 2)\"; ivers=\$(ls -1 \"/usr/local/Caskroom/\${app}/.metadata/\" | tr '\n' ' ' | sed -e 's/ \$//'); aivers=(\${ivers}); nvers=\$(echo \${#aivers[@]}); echo \"* \${app}: \${ivers} -> \${cver}\"; if [[ \${nvers} -eq 1 ]]; then echo \"\${ivers}\" | grep -q \"^\${cver}\$\" && { continue; }; fi; brew cask uninstall \"\${app}\" --force; brew cask install \"\${app}\"; done"
 
 # Docker-machine
 alias dm='docker-machine start dev && eval $(docker-machine env dev)'
 
 # Git
 alias gu='git up'
-alias hf='gss; gco master; gu; git flow hotfix start "$(($(git tag | ag \^v\\d+$ | sort | tail -n 1 | cut -d v -f 2) + 1))" && gsp'
 
 # Heroku
 alias hpa='hp addons:open'
@@ -81,187 +80,222 @@ zs() {
 	done
 }
 
-chf() {
-  HOTFIX_BRANCH=$(git branch | grep hotfix | cut -d ' ' -d '*' -f 2)
-  git checkout $HOTFIX_BRANCH
-  gup
-  gm master -m 'Merge master into hotfix branch'
+hf() {
+  git diff --exit-code > /dev/null && working=clean || working=dirty
+  git diff --cached --exit-code > /dev/null && staged=clean || staged=dirty
+
+  [ $staged = 'dirty' -a $working = 'dirty' ] && gs -k -u -q
+  [ $staged = 'dirty' -o $working = 'dirty' ] && gs -q
+
   gco master
-  gm $HOTFIX_BRANCH -m 'Hotfix'
-  git tag v$(echo $HOTFIX_BRANCH | cut -d '/' -f 2)
-  gco $HOTFIX_BRANCH
-  git push
-  hub pull-request -m Hotfix
-  while [ "$(hub ci-status master)" = "pending" ] || [ "$(hub ci-status master)" = "no status" ]; do sleep 1; done
+  gup
+  git flow hotfix start "$(($(git tag | ag \^v\\d+$ | sort | tail -n 1 | cut -d v -f 2) + 1))"
+
+  [ $staged = 'dirty' ] && gsp && giu
+  [ $working = 'dirty' ] && gsp
+}
+
+chf() {
+  gsw
+  gup
+  hotfix_branch=$(git branch | ag 'hotfix' | sed -e 's/^[* ]*//g')
+  hotfix_number=$(echo $hotfix_branch | sed -e 's/^hotfix\///g')
+  gco $hotfix_branch || return 1
+  git push || return 1
+  hub pull-request -m "Hotfix $hotfix_number" || return 1
+  gco master || return 1
+  git flow hotfix finish $hotfix_number -m "Hotfix $hotfix_number" || return 1
+  echo "And now, we wait..."
+  while [ "$(hub ci-status $hotfix_branch)" = "pending" ] || [ "$(hub ci-status $hotfix_branch)" = "no status" ]; do sleep 1; done
+  echo "And now, we push..."
   git push --tags origin master
-  git push origin $HOTFIX_BRANCH
 }
 
 gup() {
   startingBranch=$(git rev-parse --abbrev-ref HEAD)
 
-  git diff --exit-code > /dev/null
-  working=$?
+  git diff --exit-code > /dev/null && working=clean || working=dirty
+  git diff --cached --exit-code > /dev/null && staged=clean || staged=dirty
 
-  git diff --cached --exit-code
-  staged=$?
+  [ $staged = 'dirty' -a $working = 'dirty' ] && gs -k -u -q
+  [ $staged = 'dirty' -o $working = 'dirty' ] && gs -q
 
-  if [ "$working" -eq "1" ]; then
-    gs -k -u -q
-  fi
-
-  if [ "$staged" -eq "1" ]; then
-    gs -q
-  fi
-
-  gf
+  gf --tags
 
   for branch in $(git for-each-ref --format="%(refname:short) %(push:track)" refs/heads | ag '\]$' | cut -d ' ' -f 1); do
-    git checkout $branch || return 1
-    git pull || return 1
+    git checkout -q $branch || return 1
+    git pull -q || return 1
   done
 
-  gb --merged develop | ag -v '^[* ] (develop|master)$' | xargs git branch -d
+  git branch --merged develop | ag -v '^(\*|[* ]*(develop|master)$)' | sed -e 's/^[* ]*//g' | xargs git branch -q -d || return 1
 
-  gco $startingBranch || return 1
+  gco -q $startingBranch
 
-  if [ "$staged" -eq "1" ]; then
-    gsp
-    giu
-  fi
-
-  if [ "$working" -eq "1" ]; then
-    gsp
-  fi
+  [ $staged = 'dirty' ] && gsp && giu
+  [ $working = 'dirty' ] && gsp
+  true
 }
 
 # FEATURE STARTER #
 #-----------------#
 
 f() {
+  feature_number=$(trim $*)
+  [ -z $feature_number ] && echo 'Usage: f <feature_number>' && return
+
+  git diff --exit-code > /dev/null && working=clean || working=dirty
+  git diff --cached --exit-code > /dev/null && staged=clean || staged=dirty
+
+  [ $staged = 'dirty' -a $working = 'dirty' ] && gs -k -u -q
+  [ $staged = 'dirty' -o $working = 'dirty' ] && gs -q
+
   gup
-  gs
-  if [ "$(gb | sed -e 's/[* ] //g' | grep -c "^feature/.*$*")" -ne "1" ]; then
-    echo "Ambiguous or invalid argument"
-    return
+
+  count="$(gb | sed -e 's/[* ] //g' | grep -c "^feature/$feature_number")"
+  if [ $count -ne "1" ]; then
+    if [ $count -eq "0" ]; then
+      # No local branch found. Search remote tracking branches
+      count="$(gb -r | grep '^[* ] origin' | sed -e 's/[* ] origin\///g' | grep -c "^feature/$feature_number")"
+      if [ $count -ne "1" ]; then
+        if [ $count -eq "0" ]; then
+          # No remote branch found. Create new branch
+           branch_name=$(hub issue -f $'%I %t\n' | grep "^$feature_number " | sed -e 's/[^a-z0-9-]/_/gi' -e 's/[^A-Z]\([A-Z]\)/_\L\1/g' -e 's/\([A-Z]\)/\L\1/g' -e 's/__*/_/g' -e 's/^_//' -e 's/_$//g')
+          if [ $(echo $branch_name | wc -l) -eq 1 ]; then
+            gco -b "feature/$branch_name" develop
+          else
+            echo "Feature $feature_number not found on Github"
+            return
+          fi
+        else
+          echo "Multiple remote branches for feature $feature_number"
+          return
+        fi
+      else
+        F_BRANCH=$(gb -r | grep '^[* ] origin' | sed -e 's/[* ] origin\///g' | grep "^feature/$feature_number")
+      fi
+    else
+      echo "Multiple local branches for feature $feature_number"
+      return
+    fi
+  else
+    F_BRANCH=$(gb | sed -e 's/[* ] //g' | grep "^feature/.*$feature_number")
   fi
-  F_BRANCH=$(gb | sed -e 's/[* ] //g' | grep "^feature/.*$*")
 
   # Check out branch
   gco $F_BRANCH &&
   bundle install | grep -v '^Us'
   dbs
+
+  [ $staged = 'dirty' ] && gsp && giu
+  [ $working = 'dirty' ] && gsp
 }
 
-ff() { gs && gup && git flow feature start $* && gsp && dbs }
+sz() {
+  if [ ! -e .zeus.dead ]; then
+    touch .zeus.dead
+    kz
+  fi
+}
 
-# Drop unused databases
-dbc() {
-  F_DBS=$(psql -l -t | cut -d'|' -f1 | sed -e 's/ //g' -e '/^$/d' | egrep 'occsn_\w{32}')
-  F_FEATURES=$(for line in $(gb | sed -e 's/[* ] //g' | grep '^feature/'); do; echo occsn_$(echo $line | md5); done)
-  kz
-  comm -23 <(echo $F_DBS | sort) <(echo $F_FEATURES | sort) | xargs -I % sh -c 'echo "Dropping database %"; dropdb %;'
+dbs() {
+  if psql -tl | cut -d \| -f 1 | grep -wq 'occsn_dump'; then
+    # Dump exists.
+    if psql -tl | cut -d \| -f 1 | grep -wq 'occsn'; then
+      # Dev exist?
+      latest=$(trim $(psql -tc 'SELECT MAX(version) FROM schema_migrations' occsn_dump))
+      db_migrations=$(for i in $(psql -tc "SELECT * from schema_migrations WHERE CAST(version AS BIGINT) > $latest" occsn); do echo "$(trim $i)"; done | sort)
+      fs_migrations=$(for i in $(ls db/migrate | cut -d '_' -f 1 | awk "\$1 > $latest"); do echo "$(trim $i)"; done | sort)
+
+      if [ ! -z "$(comm <(echo $db_migrations) <(echo $fs_migrations) -23)" ]; then
+        # Database has migrations not in the FS. Reset db
+        dbr
+      elif [ ! -z "$(comm <(echo $db_migrations) <(echo $fs_migrations) -13)" ]; then
+        # FS has migrations not in db. Run db:migrate
+        dbm
+      fi
+    else
+      # Dev doesn't exist, create it
+      dbr
+    fi
+ else
+    # Dump doesn't exist, fetch it
+  	dbu
+  fi
 }
 
 # Recreate and migrate database
-_dbr() {
-  F_FEATURE=occsn_$(git rev-parse --abbrev-ref HEAD | md5)
-
-  # Create and migrate new database, and recreate test databases.
-  dropdb --if-exists $F_FEATURE
-  createdb -T occsn $F_FEATURE
-  _dbm
-}
-
 dbr() {
-  touch .zeus.dead
-  kz
-  _dbr
-  rm -f .zeus.dead
-}
-
-_dbm() {
-  rm -f db/schema.rb
-  rake db:migrate
+  sz
+  # Create and migrate new database, and recreate test databases.
+  dropdb --if-exists occsn
+  createdb -T occsn_dump occsn
+  dbm
   rake db:seed patch_operators_hosts after_party:run
+  rm -f .zeus.dead
 }
 
 dbm() {
-  touch .zeus.dead
-  kz
-  _dbm
-  rm -f .zeus.dead
-}
-
-_dbt() {
-  rake parallel:drop parallel:create parallel:load_schema
+  rm -f db/schema.rb
+  if [ -z $(pgrep prerake) ]; then
+    rake db:migrate
+  else
+    z r db:migrate
+  fi
 }
 
 dbt() {
-  touch .zeus.dead
-  kz
-  _dbt
-  rm -f .zeus.dead
-}
+  if psql -tl | cut -d \| -f 1 | grep -wq 'occsn_test'; then
+    latest=$(trim $(psql -tc 'SELECT MAX(version) FROM schema_migrations' occsn_dump))
+    db_migrations=$(for i in $(psql -tc "SELECT * from schema_migrations WHERE CAST(version AS BIGINT) > $latest" occsn_test); do echo "$(trim $i)"; done | sort)
+    fs_migrations=$(for i in $(ls db/migrate | cut -d '_' -f 1 | awk "\$1 > $latest"); do echo "$(trim $i)"; done | sort)
 
-_dbs() {
-  F_DBS=$(psql -l -t | cut -d'|' -f1 | sed -e 's/ //g' -e '/^$/d' | (egrep 'occsn_\w{32}') || true) || return 1
-  F_FEATURE=occsn_$(git rev-parse --abbrev-ref HEAD | md5)
-  if [ "$(grep $F_FEATURE <<< $F_DBS | wc -l)" -ne "1" ]; then
-    dbs
-  fi
-}
-
-# Setup database - Does dbc, then dbr. Asks to do dbr or dbm in case database already exists.
-dbs() {
-  touch .zeus.dead
-  kz
-
-  F_DBS=$(psql -l -t | cut -d'|' -f1 | sed -e 's/ //g' -e '/^$/d' | (egrep 'occsn_\w{32}') || true) || return 1
-  F_FEATURE=occsn_$(git rev-parse --abbrev-ref HEAD | md5)
-
-  # Create database
-  DROP=y
-  if [ "$(grep $F_FEATURE <<< $F_DBS | wc -l)" -eq "1" ]; then
-    read -k 1 "?Database $F_FEATURE already exists. Drop it? "
-    echo
-    DROP=$REPLY
-    if [[ ! $DROP =~ ^[Yy]$ ]]; then
-      read -k 1 "?Apply migrations and stuff? "
-      echo
-      MIGRATE=$REPLY
+    if [ ! -z "$(comm <(echo $db_migrations) <(echo $fs_migrations) -23)" ]; then
+      # Database has migrations not in the FS. Reset db
+      dbtr
+    elif [ ! -z "$(comm <(echo $db_migrations) <(echo $fs_migrations) -13)" ]; then
+      # FS has migrations not in db. Run db:migrate
+      dbtm
     fi
-  fi
-  read -k 1 "?Initialize test databases? "
-  echo
-  TESTPREPARE=$REPLY
-
-  if [[ $DROP =~ ^[Yy]$ ]]; then
-    _dbr
   else
-    if [[ $MIGRATE =~ ^[Yy]$ ]]; then
-      _dbm
-    fi
+    dbtr
   fi
-  if [[ $TESTPREPARE =~ ^[Yy]$ ]]; then
-    _dbt
-  fi
+}
+
+dbtr() {
+  sz
+  rake parallel:drop parallel:create parallel:load_schema
   rm -f .zeus.dead
+}
+
+dbtm() {
+  if [ -z $(pgrep prerake) ]; then
+    z r parallel:migrate
+    kz
+  else
+    rake parallel:migrate
+    rm -f .zeus.dead
+  fi
 }
 
 # Drops all feature databases and reloads Occasion database
 dbu() {
-  touch .zeus.dead
-  kz
-  dropdb --if-exists occsn > /dev/null && createdb occsn && \
-  psql -l -t | cut -d'|' -f1 | sed -e 's/ //g' -e '/^$/d' | egrep 'occsn_\w{32}' | xargs -L 1 dropdb
+  sz
+  dropdb --if-exists occsn > /dev/null &&
+  dropdb --if-exists occsn_dump > /dev/null && createdb occsn_dump && \
   aria2c -s10 -x10 -k1M -d /tmp -o dump $(heroku pg:backups:public-url -r production) && \
-  pg_restore /tmp/dump --no-acl --no-owner -d occsn -j 8 && \
-  rm -f /tmp/dump
-  dbs
+  pg_restore /tmp/dump --no-acl --no-owner -d occsn_dump -j 8 && \
+  rm -f /tmp/dump &&
+  dbr
 }
 
-export PATH="$PATH:$HOME/bin:$HOME/.rvm/bin" # Add RVM to PATH for scripting
+trim() {
+    local var="$*"
+    var="${var#"${var%%[![:space:]]*}"}"   # remove leading whitespace characters
+    var="${var%"${var##*[![:space:]]}"}"   # remove trailing whitespace characters
+    echo -n "$var"
+}
+
+export NVM_DIR="$HOME/.nvm"
+. "/usr/local/opt/nvm/nvm.sh"
 
 test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
-[[ -s "$HOME/.avn/bin/avn.sh" ]] && source "$HOME/.avn/bin/avn.sh" # load avn
